### ISSUE TITLE
Peer-To-Peer Code Review: 

### ISSUE THREAD

**Issue by ahzamir** [ehs9nino/portfolio#14]
### Hey @ehs9nino  good job so far and your project is looking awessom, there are some issues you still need to work on them to complete your project:

-  The pop-up window for the mobile version is looking to be positioned in the wrong place, we suggest making it align-center.
-  The button interaction is different from the Figma design, we suggest changing it according to the Figma design.
- The social icons on the first page and in the last page do not have links, if you can make it a link so it directs to your social profiles it would be better.
    - I can see you used a list and image tags, you can change your list tag to an anchor tag (`<a>`) to make it a link.
    - https://github.com/ehs9nino/portfolio/blob/ce36106bea90e222243c39de7ca267d561e90d61/index.html#L46-L52
![ehsan 111111111](https://user-images.githubusercontent.com/96838030/214885402-3e27f79a-1079-400d-abed-6b23bd4ec069.png)
![ehsan 44444](https://user-images.githubusercontent.com/96838030/214885798-ac7f5bd3-ec5b-4a3b-bc2c-e6a4c5221eba.png)

- The header navbar menu does not have links, I suggest making it an anchor tag (`<a>`) and giving it a link to your pages using the id of the page ( `href="#about"` ).
  - https://github.com/ehs9nino/portfolio/blob/ce36106bea90e222243c39de7ca267d561e90d61/index.html#L23-L28
![ehsan 22222222](https://user-images.githubusercontent.com/96838030/214885876-c7edb20b-e171-4ccf-a324-caf83c03f044.png)

- The pop-up model is not correctly aligned to the page, kindly make it centered.
![ehsan 0000](https://user-images.githubusercontent.com/96838030/214886075-ad30f615-611c-4b75-9607-d41218ab3a8f.png)

**Comment by ehs9nino** [comment]
@ahzamir thanks for the review, I will fix it now.
